import { createLocalId } from './storage'

export const WORK_ORDER_STORAGE_KEY = 'rubik.erp.workOrders'

export const WORK_ORDER_STATUSES = [
  'Borrador',
  'Pendiente',
  'En proceso',
  'En revisión',
  'Aprobada',
  'Finalizada',
  'Pausada',
  'Rechazada',
]

export const WORK_ORDER_PRIORITIES = ['Baja', 'Media', 'Alta', 'Urgente']

export const WORK_ORDER_AREAS = [
  'Ventas',
  'Ventas Públicas',
  'Ventas Privadas',
  'Licitaciones',
  'Marketing',
  'Diseño',
  'Diseño Imprenta',
  'Producción',
  'Taller',
  'Instalaciones',
  'Administración',
  'Contabilidad',
  'Finanzas',
  'Gerencia',
  'Desarrollo',
  'Operaciones',
  'Compras',
  'Bodega',
  'Postventa',
]

export const WORK_ORDER_TYPES = [
  'Diseño gráfico',
  'Producción gráfica',
  'Cotización',
  'Licitación',
  'Instalación',
  'Administrativo',
  'Contable',
  'Marketing',
  'Desarrollo',
  'Compra',
  'Bodega',
  'Postventa',
  'Otro',
]

export const emptyWorkOrder = {
  id: '',
  title: '',
  type: 'Producción gráfica',
  client: '',
  company: '',
  quoteNumber: '',
  requesterName: '',
  requesterEmail: '',
  requesterRole: '',
  assigneeName: '',
  assigneeEmail: '',
  assigneeRole: '',
  sourceArea: 'Ventas',
  targetArea: 'Diseño',
  priority: 'Media',
  status: 'Pendiente',
  dueDate: '',
  description: '',
  requirements: '',
  deliverables: '',
  observations: '',
  createdAt: '',
  updatedAt: '',
}

const getDateOffset = (days) => {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

export const normalizeWorkOrder = (workOrder = {}) => {
  const requesterName = workOrder.requesterName || workOrder.requestedBy || ''
  const assigneeName = workOrder.assigneeName || workOrder.assignedTo || ''

  return {
    ...emptyWorkOrder,
    ...workOrder,
    id: workOrder.id || createLocalId('ot'),
    title: workOrder.title || '',
    type: workOrder.type || 'Producción gráfica',
    client: workOrder.client || workOrder.cliente || '',
    company: workOrder.company || workOrder.empresa || '',
    quoteNumber: String(workOrder.quoteNumber || workOrder.numeroCotizacion || ''),
    requesterName,
    requesterEmail: workOrder.requesterEmail || '',
    requesterRole: workOrder.requesterRole || '',
    assigneeName,
    assigneeEmail: workOrder.assigneeEmail || '',
    assigneeRole: workOrder.assigneeRole || '',
    sourceArea: workOrder.sourceArea || 'Ventas',
    targetArea: workOrder.targetArea || 'Diseño',
    priority: workOrder.priority || 'Media',
    status: workOrder.status || 'Pendiente',
    dueDate: workOrder.dueDate || '',
    description: workOrder.description || '',
    requirements: workOrder.requirements || '',
    deliverables: workOrder.deliverables || '',
    observations: workOrder.observations || '',
    createdAt: workOrder.createdAt || new Date().toISOString(),
    updatedAt: workOrder.updatedAt || new Date().toISOString(),
  }
}

export const mockWorkOrders = [
  normalizeWorkOrder({
    title: 'Diseño propuesta municipal',
    type: 'Licitación',
    client: 'Municipalidad',
    company: 'Cliente público',
    quoteNumber: '8103',
    requesterName: 'Erick Cabrera',
    requesterEmail: 'erick@rubikcreaciones.cl',
    requesterRole: 'Venta Pública',
    assigneeName: 'Mathias Olavarria',
    assigneeEmail: 'm.olavarria@rubikcreaciones.cl',
    assigneeRole: 'Diseño / Publicidad',
    sourceArea: 'Ventas Públicas',
    targetArea: 'Diseño',
    priority: 'Alta',
    status: 'En proceso',
    dueDate: getDateOffset(3),
    description: 'Preparar propuesta gráfica y respaldo visual para cotización.',
    requirements: 'Revisar medidas, materialidad, logo y estilo solicitado.',
    deliverables: 'Mockup visual, descripción técnica y archivo editable si aplica.',
  }),
  normalizeWorkOrder({
    title: 'Revisión de costos para producción',
    type: 'Producción gráfica',
    client: 'Cliente interno',
    company: 'Rubik Creaciones',
    quoteNumber: '8104',
    requesterName: 'Jorge Gutiérrez',
    requesterEmail: 'jgutierrez@rubikcreaciones.cl',
    requesterRole: 'Diseño / Diseño Imprenta',
    assigneeName: 'Ignacio Martínez',
    assigneeEmail: 'Ignacio.m@rubikcreaciones.cl',
    assigneeRole: 'Jefe de taller',
    sourceArea: 'Diseño Imprenta',
    targetArea: 'Taller',
    priority: 'Media',
    status: 'Pendiente',
    dueDate: getDateOffset(5),
    description: 'Validar factibilidad técnica y costos base antes de enviar propuesta.',
    requirements: 'Confirmar materiales, tiempos, merma y disponibilidad.',
    deliverables: 'Costo validado y observaciones de producción.',
  }),
  normalizeWorkOrder({
    title: 'Campaña de redes para lanzamiento',
    type: 'Marketing',
    client: 'Rubik Creaciones',
    company: 'Rubik Creaciones SPA',
    quoteNumber: '',
    requesterName: 'Benjamin Rojas',
    requesterEmail: 'brojas.romero@rubikcreaciones.cl',
    requesterRole: 'Gerencia / Dueño',
    assigneeName: 'Mathias Olavarria',
    assigneeEmail: 'm.olavarria@rubikcreaciones.cl',
    assigneeRole: 'Diseño / Publicidad',
    sourceArea: 'Gerencia',
    targetArea: 'Marketing',
    priority: 'Urgente',
    status: 'En revisión',
    dueDate: getDateOffset(-1),
    description: 'Armar piezas y parrilla de contenidos para campaña digital interna.',
    requirements: 'Definir canales, tono, calendario y piezas gráficas principales.',
    deliverables: 'Calendario de publicaciones, copies y diseño base para redes sociales.',
  }),
  normalizeWorkOrder({
    title: 'Preparar despacho e instalación',
    type: 'Instalación',
    client: 'Comercial Sur',
    company: 'Comercial Sur Ltda.',
    quoteNumber: '8105',
    requesterName: 'Rodrigo Sepúlveda',
    requesterEmail: 'rsepulveda@rubikcreaciones.cl',
    requesterRole: 'Jefe Venta',
    assigneeName: 'Ignacio Martínez',
    assigneeEmail: 'Ignacio.m@rubikcreaciones.cl',
    assigneeRole: 'Jefe de taller',
    sourceArea: 'Ventas',
    targetArea: 'Instalaciones',
    priority: 'Alta',
    status: 'Borrador',
    dueDate: getDateOffset(8),
    description: 'Coordinar equipo, herramientas y ventana horaria para instalación gráfica.',
    requirements: 'Validar dirección, permisos de acceso y responsable en terreno.',
    deliverables: 'Orden de instalación lista con checklist operativo.',
  }),
]
