export const colors = {
  background: '#0f172a',
  backgroundSoft: '#111827',
  backgroundPanel: '#182033',
  surface: '#ffffff',
  surfaceMuted: '#f8fafc',
  surfaceTint: '#eef2ff',
  border: '#e2e8f0',
  borderDark: '#263244',
  text: '#0f172a',
  textMuted: '#64748b',
  textSoft: '#94a3b8',
  textOnDark: '#f8fafc',
  primary: '#3b82f6',
  primaryDark: '#1d4ed8',
  primarySoft: '#dbeafe',
  accent: '#7c3aed',
  accentSoft: '#ede9fe',
  success: '#16a34a',
  successSoft: '#dcfce7',
  danger: '#dc2626',
  dangerSoft: '#fee2e2',
  warning: '#f59e0b',
  warningSoft: '#fef3c7',
  info: '#0891b2',
  infoSoft: '#cffafe',
  neutral: '#64748b',
  neutralSoft: '#f1f5f9',
}

export const statusPalette = {
  Borrador: { background: colors.neutralSoft, color: colors.neutral },
  Pendiente: { background: colors.warningSoft, color: '#92400e' },
  'En proceso': { background: colors.primarySoft, color: colors.primaryDark },
  'En revision': { background: colors.accentSoft, color: colors.accent },
  'En revisión': { background: colors.accentSoft, color: colors.accent },
  Aprobada: { background: colors.successSoft, color: colors.success },
  Aprobado: { background: colors.successSoft, color: colors.success },
  Finalizada: { background: colors.successSoft, color: colors.success },
  Pagado: { background: colors.successSoft, color: colors.success },
  Pagada: { background: colors.successSoft, color: colors.success },
  'Pago parcial': { background: colors.warningSoft, color: '#92400e' },
  'Sin pagar': { background: colors.warningSoft, color: '#92400e' },
  'Por cobrar': { background: colors.primarySoft, color: colors.primaryDark },
  Emitida: { background: colors.primarySoft, color: colors.primaryDark },
  Enviada: { background: colors.infoSoft, color: colors.info },
  Baja: { background: colors.neutralSoft, color: colors.neutral },
  Media: { background: colors.primarySoft, color: colors.primaryDark },
  Alta: { background: colors.warningSoft, color: '#92400e' },
  Urgente: { background: colors.dangerSoft, color: colors.danger },
  Vencido: { background: colors.dangerSoft, color: colors.danger },
  Vencida: { background: colors.dangerSoft, color: colors.danger },
  Rechazada: { background: colors.dangerSoft, color: colors.danger },
  Perdida: { background: colors.dangerSoft, color: colors.danger },
}

export const getStatusColors = (status) => statusPalette[status] || { background: colors.neutralSoft, color: colors.neutral }
